name: ExplosionControl
description: ${description}
authors: [ TehBrian ]
website: https://github.com/TehBrian/ExplosionControl

version: ${version}
main: xyz.tehbrian.explosioncontrol.ExplosionControl
api-version: 1.17
